DROP TABLE IF EXISTS users, categories, compilations, events, events_compilations, requests CASCADE;

CREATE TABLE  IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    name  VARCHAR(250)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS categories
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    name VARCHAR(250)                            NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    pinned BOOLEAN                                 NOT NULL,
    title  VARCHAR(50)                             NOT NULL
);
CREATE TABLE IF NOT EXISTS events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    annotation        VARCHAR(2000)                           NOT NULL,
    description       VARCHAR(7000)                           NOT NULL,
    eventDate         TIMESTAMP WITHOUT TIME ZONE,
    lat               FLOAT                                   NOT NULL,
    lon               FLOAT                                   NOT NULL,
    paid              BOOLEAN                                 NOT NULL,
    participantLimit  INTEGER                                 NOT NULL,
    requestModeration BOOLEAN                                 NOT NULL,
    title             VARCHAR(120)                            NOT NULL,
    state             VARCHAR                                 NOT NULL,
    createdOn         TIMESTAMP WITHOUT TIME ZONE,
    publishedOn       TIMESTAMP WITHOUT TIME ZONE,
    initiator_id        BIGINT REFERENCES users (id) ON DELETE CASCADE,
    categories_id     BIGINT REFERENCES categories (id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS events_compilations
(
    events_id       BIGINT REFERENCES events (id) ON DELETE CASCADE,
    compilations_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    created      TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(255)                            NOT NULL,
    requester_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    events_id    BIGINT REFERENCES events (id) ON DELETE CASCADE
);