version: '3.1'
services:
  stats-server:
    build: ./stats-service/service
    image: service
    container_name: service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB= events
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= 1234

  ewm-service:
    build: ./main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine



